### ISSUE TITLE
今天更新的版本依然是 签到失败: 人机校验失败

### ISSUE THREAD

**Issue by klcb2010** [CMDQ8575/Xiaomi-Community-AutoTask#9]
![截屏图片](https://github.com/CMDQ8575/Xiaomi-Community-AutoTask/assets/32628414/bca3f718-1810-46fb-bc2e-28f7fe4f6623)

**Comment by CMDQ8575** [comment]
我回滚了，现在上面用的还是上周的版本。目前由于加密存在兼容性问题导致基本无法跨Python和gcc版本运行，等修复之后再更新了

**Comment by skywk** [comment]
回滚的版本签到也失败。

**Comment by CMDQ8575** [comment]
是啊，上周的版本就是后面多了滑动验证码所以签到肯定失败

**Comment by kazsy** [comment]
加油
